### ISSUE TITLE
Error Maya2018/scripts/others/pluginWin.mel 290: (zMayaUtils) when loading plugin

### ISSUE THREAD

**Issue by arraybercov** [zewt/zMayaTools#1]
Hi,

I ran install.bat and when i go to the plugin manager of maya 2018.5 to load the plugin I get this error:

Error Error: file C:/.../Maya2018/scripts/others/pluginWin.mel 290: (zMayaUtils) when loading plugin

Any ideas?

**Comment by arraybercov** [comment]
More info from log: 

// Warning: file: C:/Program Files/Autodesk/Maya2018/scripts/others/pluginWin.mel line 290: Failed to call script initialize function // 
// Error: file: C:/Program Files/Autodesk/Maya2018/scripts/others/pluginWin.mel line 290:  (zMayaUtils) //

**Comment by arraybercov** [comment]
And when rebooting maya I got this

// Error: file: C:/Program Files/Autodesk/Maya2018/scripts/startup/autoLoadPlugin.mel line 35: IndexError: file C:/Users/ianbe/Documents/maya/plug-ins/zMayaTools-master/plug-ins/zMayaUtils.py line 42: list index out of range // 
// Warning: file: C:/Program Files/Autodesk/Maya2018/scripts/startup/autoLoadPlugin.mel line 35: Failed to call script initialize function // 
// Error: file: C:/Program Files/Autodesk/Maya2018/scripts/startup/autoLoadPlugin.mel line 35:  (zMayaUtils) //

**Comment by zewt** [comment]
See if ee162b19280e77e3d960cc7b010fb9d41386a300 helps.  If you still get errors on load, make sure History > Show Stack Trace is enabled in the script editor window.

**Comment by zewt** [comment]
Let me know if you're still having issues.
