### ISSUE TITLE
name 'pymel' is not defined #   in maya 2020

### ISSUE THREAD

**Issue by mostlyhuman** [zewt/zMayaTools#2]
Getting this error after things had been working fine.  I havent changed anything with the configuration so not sure what the deal is.

pymel.internal.factories.callback
# Error: name 'pymel' is not defined
# Traceback (most recent call last):
#   File "<maya console>", line 1, in <module>
# NameError: name 'pymel' is not defined #

**Comment by zewt** [comment]
Do you have any more information, when does it happen?  The only place the word "pymel" is actually used in the code is in imports, which would give a different error if there was a problem.  Maybe you can get more info by turning on "echo all commands" in the script editor History menu.

**Comment by mostlyhuman** [comment]
Thank you, I reinstalled the plugin and it seems to have fixed it but now I
have another issue where sometimes I get this error using Retarget
Blendshapes, the error occurs when I press the button to actually do the
retarget

# Error: sequence item 0: expected string, Mesh found
# Traceback (most recent call last):
#   File "C:\Program
Files\Autodesk\Maya2020\Python\lib\site-packages\pymel\internal\factories.py",
line 830, in callback
#     res = origCallback(*newargs)
#   File
"J:\Users\Clayd\OneDrive\Documents\maya\zMayaTools-master\scripts\zMayaTools\maya_helpers.py",
line 175, in apply
#     self.option_box_apply()
#   File
"J:\Users\Clayd\OneDrive\Documents\maya\zMayaTools-master\scripts\zMayaTools\blend_shape_retargetting.py",
line 597, in option_box_apply
#     len(src_blend_shape_targets), ', '.join(src_blend_shape_targets))
# TypeError: sequence item 0: expected string, Mesh found #

**Comment by zewt** [comment]
Reinstalling won't really do much (there's nothing to install but a small file that tells Maya where it is), let me know if you see the error again.

I'll fix the exception, but it's in an error message anyway: "Blend shape %s must have one target"  That'll happen if it's used on a blendShape deformer with multiple meshes.  That's not supported right now, it doesn't know how to figure out which mesh to use or which source mesh goes with which target mesh.  I'll see if it can let you pick which mesh to use when that happens.

**Comment by zewt** [comment]
You can select which mesh to retarget now if you have more than one mesh on a blendShape.  You'll need to do each mesh separately so it knows which mesh goes with which.  32b7823c

**Comment by mostlyhuman** [comment]
perfect, thank you so much Glenn!
