### ISSUE TITLE
zMayaTools Manual installation

### ISSUE THREAD

**Issue by MrHakko** [zewt/zMayaTools#4]
Hello mate,
hope you are well.

I've just downloaded your latest zMayaTools. I want to give it a try on Split Blend Shape, it seems to be a great tool and saves a lot of time :D 

But I tried to install it and after running the .bat file, it says the installation is complete, but I can't find it on my plug-in manager.

Can you explain how could I install this manually or if you have any other solutions?

Many, many thanks

**Comment by zewt** [comment]
Just saw this now.  If you're still having trouble, what directory is it stored in?  Maya module files seem to not work with non-ASCII directory names, eg. if it's somewhere in your user directory and your username has accents in it.
